[package]
name = "kamera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icrate = { version = "0.0.3", features = ["Foundation", "Foundation_NSArray", "Foundation_NSNumber", "Foundation_NSMutableDictionary"] }
objc2 = { version = "0.4.0", features = ["malloc"] }

[dev-dependencies]
softbuffer = "*"
winit = "*"